### ISSUE TITLE
Enhancement: Make base classes more compatible with type analysis

### ISSUE THREAD

**Issue by Rey092** [litestar-org/advanced-alchemy#242]
### Summary

There is some libraries and also custom code that can analyze attribute types in runtime to do something. 
It can be used for conversion (persistance model -> domain entity) / etc.

Please consider to move this row https://github.com/litestar-org/advanced-alchemy/blob/3f7fee382fb2bdc4adf2228eaa487cc51d5ad8a8/advanced_alchemy/base.py#L36 from TYPE_CHECKING.

It would simplify type analysis of models.

### Basic Example

if TYPE_CHECKING:
    from sqlalchemy.sql import FromClause
   ...
------->>>
from sqlalchemy.sql import FromClause
if TYPE_CHECKING:
   ...

### Drawbacks and Impact

I don't think there would be any real drawbacks.

**Comment by provinzkraut** [comment]
This would only really help you if you ensure that all other type annotations are also available at runtime which, generally, isn't a thing you can rely on. Virtually all libraries that use type annotations at runtime account for this fact (e.g. SQLAlchemy itself, Pydantic, msgspec, Litestar, (c)attrs, FastAPI), since requiring users to never use stringised annotations of any kind makes your library much less useful and portable.

Is there some specific problem you're hitting that can't be solve with e.g. [`get_type_hints`](https://docs.python.org/3/library/typing.html#typing.get_type_hints)?

**Comment by Rey092** [comment]
> This would only really help you if you ensure that all other type annotations are also available at runtime which, generally, isn't a thing you can rely on. Virtually all libraries that use type annotations at runtime account for this fact (e.g. SQLAlchemy itself, Pydantic, msgspec, Litestar, (c)attrs, FastAPI), since requiring users to never use stringised annotations of any kind makes your library much less useful and portable.
> 
> Is there some specific problem you're hitting that can't be solve with e.g. [`get_type_hints`](https://docs.python.org/3/library/typing.html#typing.get_type_hints)?

Yeah, problem with inability to use it.
`
from typing import get_type_hints
from advanced_alchemy.base import BigIntAuditBase
get_type_hints(BigIntAuditBase)
`

**Comment by Rey092** [comment]
Also pydantic and company doing something like that:
![image](https://github.com/user-attachments/assets/c3e43b31-a940-4cac-b824-ac58591ce718)

Similar there:
![image](https://github.com/user-attachments/assets/045c38eb-9e58-4833-91be-06a357a91a16)

But not there:
![image](https://github.com/user-attachments/assets/edd6d4c1-59ff-4192-8c56-b0821f9b1c61)

It would be perfect to do something like that too as alternative to doing an actual import
![image](https://github.com/user-attachments/assets/64c6900f-5b9c-4c1f-aa94-339df2cacc9c)

**Comment by Rey092** [comment]
https://github.com/litestar-org/advanced-alchemy/pull/243

**Comment by cofin** [comment]
closed by #243
